//
//  AutolayoutScrollViewVC.m
//  AutolayoutScrollView
//
//  Created by Daredos on 16/4/28.
//  Copyright © 2016年 Daredos. All rights reserved.
//

#import "AutolayoutScrollViewVC.h"

@interface AutolayoutScrollViewVC ()
@property (weak, nonatomic) IBOutlet UILabel *tectLabel;
@property (weak, nonatomic) IBOutlet UIScrollView *scrollView;
@end

@implementation AutolayoutScrollViewVC

- (void)viewDidLoad {
    [super viewDidLoad];

    [self.scrollView addGestureRecognizer: [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(click)]];
}

- (void)click {

    self.tectLabel.text = @"addGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecaddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizerognizer";

    if (arc4random()%3 == 0) {
        self.tectLabel.text = @"izeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRecognizeraddGestureRenizerognize";
    }
}

@end
